# rails-api/config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "postgres" } %>
  username: <%= ENV.fetch("DB_USER") { "expol" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "expol_password" } %>

development:
  <<: *default
  database: expol_development

test:
  <<: *default
  database: expol_test

production:
  <<: *default
  database: expol_production