# rails-api/config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: expol_password

development:
  <<: *default
  database: expol_development

test:
  <<: *default
  database: expol_test

production:
  <<: *default
  database: expol_production